[models]
cache_dir = "./models"

[[models.selection]]
name = "Grounding DINO + SAM 2"
type = "grounding_dino_sam"
grounding_dino_model = "IDEA-Research/grounding-dino-base"
sam_model = "facebook/sam2.1-hiera-large"

[[models.inpainting]]
name = "Stable diffusion 1.5"
type = "stable_diffusion"
model_or_checkpoint = "stable-diffusion-v1-5/stable-diffusion-inpainting"

[[models.upscaling]]
name = "Stable diffusion x4"
type = "stable_diffusion"
model_or_checkpoint = "stabilityai/stable-diffusion-x4-upscaler"

[[models.portrait_editing]]
name = "LivePortrait"
type = "liveportrait"
